// LOT-1C — finished-lot / recall-passport projector.
//
// Hooks two upstream code paths:
//   1. BAG_FINALIZED (lib/projector/index.ts) — when a workflow_bag
//      finalizes AND a finished_lots row already exists for it,
//      backfill the recall-passport projection tables.
//   2. createFinishedLot (lib/db/queries/finished-lots.ts) — when an
//      operator manually creates a finished_lots row, immediately
//      project its passport children.
//
// Plus a full rebuilder (rebuildFinishedLotPassport) wired into
// scripts/rebuild-read-models.ts.
//
// Strict invariants per LOT-1A / LOT-1B and the LOT-1C prompt:
//   - Never auto-create finished_lots from BAG_FINALIZED alone.
//     The current operator-driven createFinishedLot flow stays as
//     the only "is this lot real" arbiter; this projector enriches
//     existing lots.
//   - Never fabricate output counts. unitsProduced / displaysProduced
//     / casesProduced come from finished_lots; we project rows only
//     when the underlying count > 0.
//   - Confidence ladder:
//       HIGH    — workflow_bag.inventory_bag_id directly identifies
//                 the raw bag.
//       LOW     — only finished_lot_inputs (batch level) is known;
//                 we fan out to the bags in that batch.
//       MISSING — neither chain yields anything; we skip.
//   - Preserve existing trace_code. Once a trace_code is set on a
//     finished_lot it is never re-generated by the projector — that's
//     the customer-facing identifier and operators may have
//     hand-edited it.
//   - Supplier lot is NEVER embedded in print_payload by default.
//     LOT-1F's outbound layer will gate exposure per customer flag.
//   - Idempotent: re-running the projector on the same finished_lot
//     produces the same row set. Children are upserted on their
//     natural unique keys; PROJECTOR-source outputs are DELETE+INSERT
//     so a re-run reflects the latest counts.

import { and, eq, inArray, isNotNull, sql } from "drizzle-orm";
import type { db as Db } from "@/lib/db";
import {
  finishedLots,
  finishedLotInputs,
  finishedLotOutputs,
  finishedLotPackagingLots,
  finishedLotQcEvents,
  finishedLotRawBags,
  inventoryBags,
  materialInventoryEvents,
  workflowBags,
  products,
} from "@/lib/db/schema";
import {
  buildFinishedLotTraceCode,
  rollupRecallConfidence,
  type RecallConfidence,
} from "@/lib/production/recall-passport";

type Tx = Parameters<Parameters<typeof Db.transaction>[0]>[0] | typeof Db;

/** Source enum mirrors the SQL CHECK on finished_lot_raw_bags / _packaging_lots. */
export type RecallSource =
  | "PROJECTOR"
  | "BACKFILL"
  | "MANUAL"
  | "LEGACY_IMPORT";

export type ContributingBagLink = {
  inventoryBagId: string;
  workflowBagId: string | null;
  quantityConsumedPills: number | null;
  confidence: RecallConfidence;
  source: RecallSource;
  derivedFromEventId: string | null;
};

// ─── Pure helpers (tested directly) ───────────────────────────────────

/** Decide what trace_code a finished_lots row should carry. Preserves
 *  an existing value; falls back to `FL-<finishedLotNumber>` for new
 *  / null trace codes. */
export function deriveTraceCodeForLot(args: {
  existingTraceCode: string | null;
  finishedLotNumber: string;
}): string {
  if (args.existingTraceCode && args.existingTraceCode.trim().length > 0) {
    return args.existingTraceCode;
  }
  return buildFinishedLotTraceCode({
    finishedLotNumber: args.finishedLotNumber,
  });
}

/** Snapshot for finished_lot_outputs.print_payload. Trace code +
 *  product name + packed date + optional customer alias. Never
 *  contains supplier_lot_number. */
export function buildPrintPayload(args: {
  traceCode: string;
  productName: string | null;
  productSku: string | null;
  packedAt: Date | null;
  expiresAt: Date | null;
  finishedLotCodeAlias: string | null;
}): Record<string, unknown> {
  const payload: Record<string, unknown> = {
    source: "PROJECTOR",
    schema_version: "1.0",
    trace_code: args.traceCode,
    product_name: args.productName,
    product_sku: args.productSku,
    packed_at: args.packedAt ? args.packedAt.toISOString() : null,
    expires_at: args.expiresAt ? args.expiresAt.toISOString() : null,
  };
  if (args.finishedLotCodeAlias) {
    payload.customer_alias = args.finishedLotCodeAlias;
  }
  return payload;
}

/** Project finished_lots counts into one finished_lot_outputs row per
 *  non-zero output type. Skips zero / null counts — we never
 *  fabricate. */
export function deriveOutputRows(args: {
  unitsProduced: number;
  displaysProduced: number | null;
  casesProduced: number | null;
  traceCode: string;
  printPayload: Record<string, unknown>;
}): Array<{
  outputType: "LOOSE_UNIT" | "DISPLAY" | "MASTER_CASE";
  quantity: number;
  unit: string;
  traceCodePrinted: string;
  printPayload: Record<string, unknown>;
}> {
  const rows: Array<{
    outputType: "LOOSE_UNIT" | "DISPLAY" | "MASTER_CASE";
    quantity: number;
    unit: string;
    traceCodePrinted: string;
    printPayload: Record<string, unknown>;
  }> = [];
  if (args.unitsProduced > 0) {
    rows.push({
      outputType: "LOOSE_UNIT",
      quantity: args.unitsProduced,
      unit: "each",
      traceCodePrinted: args.traceCode,
      printPayload: args.printPayload,
    });
  }
  if (args.displaysProduced != null && args.displaysProduced > 0) {
    rows.push({
      outputType: "DISPLAY",
      quantity: args.displaysProduced,
      unit: "each",
      traceCodePrinted: args.traceCode,
      printPayload: args.printPayload,
    });
  }
  if (args.casesProduced != null && args.casesProduced > 0) {
    rows.push({
      outputType: "MASTER_CASE",
      quantity: args.casesProduced,
      unit: "each",
      traceCodePrinted: args.traceCode,
      printPayload: args.printPayload,
    });
  }
  return rows;
}

/** Given the raw inputs the projector can see, build the set of
 *  contributing-bag links to upsert. */
export function deriveContributingBags(args: {
  workflowBagId: string | null;
  workflowBagInventoryBagId: string | null;
  workflowBagPillCount: number | null;
  /** Each row from finished_lot_inputs that points at a batch. */
  batchInputs: Array<{
    batchId: string;
    qtyConsumed: number;
    derivedFromEventId: string | null;
  }>;
  /** Bags that belong to the contributing batches. */
  bagsByBatch: Record<string, Array<{ id: string; pillCount: number | null }>>;
}): ContributingBagLink[] {
  const links: ContributingBagLink[] = [];

  // HIGH-confidence direct link from workflow_bag.inventory_bag_id.
  if (args.workflowBagId && args.workflowBagInventoryBagId) {
    links.push({
      inventoryBagId: args.workflowBagInventoryBagId,
      workflowBagId: args.workflowBagId,
      quantityConsumedPills: args.workflowBagPillCount,
      confidence: "HIGH",
      source: "PROJECTOR",
      derivedFromEventId: null,
    });
  }

  // LOW-confidence batch-level inference. For each batch input row,
  // fan out to every inventory_bag in that batch. We deliberately
  // don't try to split qtyConsumed across bags — better to leave the
  // per-bag quantity null than to fabricate.
  const seen = new Set(links.map((l) => keyOf(l.inventoryBagId, l.workflowBagId)));
  for (const inp of args.batchInputs) {
    const bagsInBatch = args.bagsByBatch[inp.batchId] ?? [];
    for (const bag of bagsInBatch) {
      const k = keyOf(bag.id, args.workflowBagId);
      if (seen.has(k)) continue;
      // Same (inventory_bag, workflow_bag) was already inserted at HIGH
      // confidence — don't downgrade.
      const kNullWorkflow = keyOf(bag.id, null);
      if (seen.has(kNullWorkflow)) continue;
      links.push({
        inventoryBagId: bag.id,
        workflowBagId: args.workflowBagId,
        quantityConsumedPills: null,
        confidence: "LOW",
        source: "LEGACY_IMPORT",
        derivedFromEventId: inp.derivedFromEventId,
      });
      seen.add(k);
    }
  }

  return links;
}

function keyOf(bagId: string, workflowBagId: string | null): string {
  return `${bagId}::${workflowBagId ?? "null"}`;
}

/** Tells callers how confident a finished_lot's passport is overall.
 *  MIN across all contributing links. Empty → MISSING. */
export function summarizePassportConfidence(
  links: ContributingBagLink[],
): RecallConfidence {
  return rollupRecallConfidence(links.map((l) => l.confidence));
}

// ─── DB-touching projections ──────────────────────────────────────────

/** QC event types we project into finished_lot_qc_events. Matches
 *  the QC-1 / QC-2 set; if a new QC type lands it must be added here. */
const QC_EVENT_TYPES = [
  "PACKAGING_DAMAGE_RETURN",
  "REWORK_SENT",
  "REWORK_RECEIVED",
  "SCRAP_RECORDED",
  "SUBMISSION_CORRECTED",
] as const;

export type ProjectionResult = {
  finishedLotId: string;
  traceCode: string | null;
  rawBagsWritten: number;
  outputsWritten: number;
  packagingLotsWritten: number;
  qcEventsWritten: number;
  confidence: RecallConfidence;
  skipped: boolean;
  skipReason?: string;
};

/** Called from lib/projector/index.ts on BAG_FINALIZED. Looks up the
 *  finished_lot row that names this workflow_bag (if any) and
 *  enriches its passport. No-op when no finished_lot exists — the
 *  operator may not have created one yet. */
export async function projectFinishedLotForFinalizedBag(
  tx: Tx,
  workflowBagId: string,
  occurredAt: Date,
): Promise<ProjectionResult | null> {
  const rows = await tx
    .select({ id: finishedLots.id, packedAt: finishedLots.packedAt })
    .from(finishedLots)
    .where(eq(finishedLots.workflowBagId, workflowBagId));
  if (rows.length === 0) return null;
  const lot = rows[0]!;

  // Stamp packed_at if still null. Don't overwrite an operator-edited
  // value.
  if (lot.packedAt == null) {
    await tx
      .update(finishedLots)
      .set({ packedAt: occurredAt })
      .where(eq(finishedLots.id, lot.id));
  }

  return projectFinishedLotPassportForLot(tx, lot.id);
}

/** Called from createFinishedLot() and from the rebuilder. Idempotent. */
export async function projectFinishedLotPassportForLot(
  tx: Tx,
  finishedLotId: string,
): Promise<ProjectionResult> {
  // ── Read the finished_lot + product ───────────────────────────
  const [lot] = await tx
    .select({
      id: finishedLots.id,
      productId: finishedLots.productId,
      workflowBagId: finishedLots.workflowBagId,
      finishedLotNumber: finishedLots.finishedLotNumber,
      unitsProduced: finishedLots.unitsProduced,
      displaysProduced: finishedLots.displaysProduced,
      casesProduced: finishedLots.casesProduced,
      traceCode: finishedLots.traceCode,
      packedAt: finishedLots.packedAt,
      expiresAt: finishedLots.expiresAt,
      finishedLotCodeAlias: finishedLots.finishedLotCodeAlias,
    })
    .from(finishedLots)
    .where(eq(finishedLots.id, finishedLotId));
  if (!lot) {
    return {
      finishedLotId,
      traceCode: null,
      rawBagsWritten: 0,
      outputsWritten: 0,
      packagingLotsWritten: 0,
      qcEventsWritten: 0,
      confidence: "MISSING",
      skipped: true,
      skipReason: "finished_lot not found",
    };
  }

  // ── Ensure trace_code is set ──────────────────────────────────
  const traceCode = deriveTraceCodeForLot({
    existingTraceCode: lot.traceCode,
    finishedLotNumber: lot.finishedLotNumber,
  });
  if (lot.traceCode !== traceCode) {
    await tx
      .update(finishedLots)
      .set({ traceCode })
      .where(eq(finishedLots.id, lot.id));
  }

  // ── Resolve contributing workflow / inventory bags ────────────
  let workflowBagInventoryBagId: string | null = null;
  let workflowBagPillCount: number | null = null;
  if (lot.workflowBagId) {
    const [wb] = await tx
      .select({
        inventoryBagId: workflowBags.inventoryBagId,
      })
      .from(workflowBags)
      .where(eq(workflowBags.id, lot.workflowBagId));
    workflowBagInventoryBagId = wb?.inventoryBagId ?? null;
    if (workflowBagInventoryBagId) {
      const [bag] = await tx
        .select({ pillCount: inventoryBags.pillCount })
        .from(inventoryBags)
        .where(eq(inventoryBags.id, workflowBagInventoryBagId));
      workflowBagPillCount = bag?.pillCount ?? null;
    }
  }
  const batchInputs = await tx
    .select({
      batchId: finishedLotInputs.batchId,
      qtyConsumed: finishedLotInputs.qtyConsumed,
      derivedFromEventId: finishedLotInputs.derivedFromEventId,
    })
    .from(finishedLotInputs)
    .where(eq(finishedLotInputs.finishedLotId, lot.id));
  const bagsByBatch: Record<
    string,
    Array<{ id: string; pillCount: number | null }>
  > = {};
  if (batchInputs.length > 0) {
    const batchIds = batchInputs.map((b) => b.batchId);
    const bags = await tx
      .select({
        id: inventoryBags.id,
        batchId: inventoryBags.batchId,
        pillCount: inventoryBags.pillCount,
      })
      .from(inventoryBags)
      .where(inArray(inventoryBags.batchId, batchIds));
    for (const b of bags) {
      if (!b.batchId) continue;
      if (!bagsByBatch[b.batchId]) bagsByBatch[b.batchId] = [];
      bagsByBatch[b.batchId]!.push({ id: b.id, pillCount: b.pillCount });
    }
  }
  const links = deriveContributingBags({
    workflowBagId: lot.workflowBagId,
    workflowBagInventoryBagId,
    workflowBagPillCount,
    batchInputs: batchInputs.map((b) => ({
      batchId: b.batchId,
      qtyConsumed: b.qtyConsumed,
      derivedFromEventId: b.derivedFromEventId ?? null,
    })),
    bagsByBatch,
  });
  const rawBagsWritten = await runRawBagProjection(tx, lot.id, links);

  // ── Product context for print_payload ─────────────────────────
  let productName: string | null = null;
  let productSku: string | null = null;
  if (lot.productId) {
    const [p] = await tx
      .select({ name: products.name, sku: products.sku })
      .from(products)
      .where(eq(products.id, lot.productId));
    productName = p?.name ?? null;
    productSku = p?.sku ?? null;
  }

  // ── Outputs (LOOSE / DISPLAY / MASTER_CASE) ───────────────────
  const printPayload = buildPrintPayload({
    traceCode,
    productName,
    productSku,
    packedAt: lot.packedAt,
    expiresAt: lot.expiresAt,
    finishedLotCodeAlias: lot.finishedLotCodeAlias,
  });
  const outputRows = deriveOutputRows({
    unitsProduced: lot.unitsProduced,
    displaysProduced: lot.displaysProduced ?? null,
    casesProduced: lot.casesProduced ?? null,
    traceCode,
    printPayload,
  });
  const outputsWritten = await runOutputsProjection(tx, lot.id, outputRows);

  // ── Packaging lots + QC events ────────────────────────────────
  const contributingWorkflowBags = lot.workflowBagId ? [lot.workflowBagId] : [];
  const packagingLotsWritten = await runPackagingLotsProjection(
    tx,
    lot.id,
    contributingWorkflowBags,
  );
  const qcEventsWritten = await runQcEventsProjection(
    tx,
    lot.id,
    contributingWorkflowBags,
  );

  return {
    finishedLotId: lot.id,
    traceCode,
    rawBagsWritten,
    outputsWritten,
    packagingLotsWritten,
    qcEventsWritten,
    confidence: summarizePassportConfidence(links),
    skipped: false,
  };
}

// ─── Sub-projection helpers ───────────────────────────────────────────

async function runRawBagProjection(
  tx: Tx,
  finishedLotId: string,
  links: ContributingBagLink[],
): Promise<number> {
  if (links.length === 0) return 0;
  let written = 0;
  for (const l of links) {
    // The triple-unique uses NULLS NOT DISTINCT — Postgres 15+ — so a
    // (lot, bag, NULL) row collides with another (lot, bag, NULL),
    // and ON CONFLICT updates the existing row's qty / confidence /
    // source. Drizzle's onConflict doesn't carry NULLS-NOT-DISTINCT
    // semantics, so use raw SQL.
    await tx.execute(sql`
      INSERT INTO finished_lot_raw_bags (
        finished_lot_id, inventory_bag_id, workflow_bag_id,
        quantity_consumed_pills, confidence, source, derived_from_event_id,
        created_at, updated_at
      ) VALUES (
        ${finishedLotId}, ${l.inventoryBagId}, ${l.workflowBagId},
        ${l.quantityConsumedPills}, ${l.confidence}, ${l.source},
        ${l.derivedFromEventId}, NOW(), NOW()
      )
      ON CONFLICT (finished_lot_id, inventory_bag_id, workflow_bag_id)
      DO UPDATE SET
        quantity_consumed_pills = EXCLUDED.quantity_consumed_pills,
        confidence = EXCLUDED.confidence,
        source = EXCLUDED.source,
        derived_from_event_id = EXCLUDED.derived_from_event_id,
        updated_at = NOW()
    `);
    written += 1;
  }
  return written;
}

async function runOutputsProjection(
  tx: Tx,
  finishedLotId: string,
  rows: ReturnType<typeof deriveOutputRows>,
): Promise<number> {
  // DELETE PROJECTOR-sourced rows first so a re-run reflects current
  // counts. Operator-added rows (with print_payload->>'source' != 'PROJECTOR')
  // are preserved. Use raw SQL because Drizzle's where() doesn't
  // express jsonb operators cleanly.
  await tx.execute(sql`
    DELETE FROM finished_lot_outputs
    WHERE finished_lot_id = ${finishedLotId}
      AND (print_payload->>'source') = 'PROJECTOR'
  `);
  if (rows.length === 0) return 0;
  for (const r of rows) {
    await tx.insert(finishedLotOutputs).values({
      finishedLotId,
      outputType: r.outputType,
      quantity: r.quantity,
      unit: r.unit,
      traceCodePrinted: r.traceCodePrinted,
      printPayload: r.printPayload as unknown as object,
    });
  }
  return rows.length;
}

type PackagingLotAgg = {
  packagingLotId: string;
  materialId: string | null;
  qtySum: number;
  unit: string | null;
  firstUsedAt: Date | null;
  lastUsedAt: Date | null;
};

async function runPackagingLotsProjection(
  tx: Tx,
  finishedLotId: string,
  contributingWorkflowBags: string[],
): Promise<number> {
  if (contributingWorkflowBags.length === 0) return 0;
  // Pull every material_inventory_events row tied to one of the
  // contributing workflow bags AND carrying a packaging_lot_id.
  const events = await tx
    .select({
      packagingLotId: materialInventoryEvents.packagingLotId,
      materialId: materialInventoryEvents.packagingMaterialId,
      quantityUnits: materialInventoryEvents.quantityUnits,
      unitOfMeasure: materialInventoryEvents.unitOfMeasure,
      occurredAt: materialInventoryEvents.occurredAt,
    })
    .from(materialInventoryEvents)
    .where(
      and(
        inArray(materialInventoryEvents.workflowBagId, contributingWorkflowBags),
        isNotNull(materialInventoryEvents.packagingLotId),
      ),
    );
  const agg = new Map<string, PackagingLotAgg>();
  for (const ev of events) {
    if (!ev.packagingLotId) continue;
    const k = ev.packagingLotId;
    const existing = agg.get(k);
    const qty = ev.quantityUnits != null ? Number(ev.quantityUnits) : 0;
    if (existing) {
      existing.qtySum += qty;
      if (
        ev.occurredAt &&
        (!existing.firstUsedAt || ev.occurredAt < existing.firstUsedAt)
      ) {
        existing.firstUsedAt = ev.occurredAt;
      }
      if (
        ev.occurredAt &&
        (!existing.lastUsedAt || ev.occurredAt > existing.lastUsedAt)
      ) {
        existing.lastUsedAt = ev.occurredAt;
      }
    } else {
      agg.set(k, {
        packagingLotId: k,
        materialId: ev.materialId ?? null,
        qtySum: qty,
        unit: ev.unitOfMeasure ?? null,
        firstUsedAt: ev.occurredAt ?? null,
        lastUsedAt: ev.occurredAt ?? null,
      });
    }
  }
  if (agg.size === 0) {
    // No upstream events tie packaging lots to these workflow bags.
    // Don't guess — leave the projection empty.
    return 0;
  }
  for (const [, row] of agg) {
    await tx.execute(sql`
      INSERT INTO finished_lot_packaging_lots (
        finished_lot_id, packaging_lot_id, material_id,
        quantity_used, unit, confidence, source,
        first_used_at, last_used_at, created_at, updated_at
      ) VALUES (
        ${finishedLotId}, ${row.packagingLotId}, ${row.materialId},
        ${row.qtySum > 0 ? row.qtySum : null}, ${row.unit},
        'HIGH', 'PROJECTOR',
        ${row.firstUsedAt}, ${row.lastUsedAt}, NOW(), NOW()
      )
      ON CONFLICT (finished_lot_id, packaging_lot_id)
      DO UPDATE SET
        material_id = EXCLUDED.material_id,
        quantity_used = EXCLUDED.quantity_used,
        unit = EXCLUDED.unit,
        confidence = EXCLUDED.confidence,
        source = EXCLUDED.source,
        first_used_at = LEAST(finished_lot_packaging_lots.first_used_at, EXCLUDED.first_used_at),
        last_used_at  = GREATEST(finished_lot_packaging_lots.last_used_at, EXCLUDED.last_used_at),
        updated_at = NOW()
    `);
  }
  return agg.size;
}

async function runQcEventsProjection(
  tx: Tx,
  finishedLotId: string,
  contributingWorkflowBags: string[],
): Promise<number> {
  if (contributingWorkflowBags.length === 0) return 0;
  // Single INSERT … SELECT keeps the round-trip count to one and
  // sidesteps drizzle's strict pg-enum inArray typing.
  const inserted = (await tx.execute(sql`
    INSERT INTO finished_lot_qc_events (
      finished_lot_id, workflow_event_id, event_type, occurred_at, created_at
    )
    SELECT
      ${finishedLotId}, e.id, e.event_type::text, e.occurred_at, NOW()
    FROM workflow_events e
    WHERE e.workflow_bag_id = ANY(${contributingWorkflowBags}::uuid[])
      AND e.event_type::text = ANY(${QC_EVENT_TYPES as unknown as string[]}::text[])
    ON CONFLICT (finished_lot_id, workflow_event_id) DO NOTHING
    RETURNING 1
  `)) as unknown as Array<unknown>;
  return Array.isArray(inserted) ? inserted.length : 0;
}

// ─── Full rebuilder ────────────────────────────────────────────────────

export type RebuildResult = {
  scanned: number;
  projected: number;
  skipped: number;
  totalRawBags: number;
  totalOutputs: number;
  totalPackagingLots: number;
  totalQcEvents: number;
};

/** Walk every finished_lots row and run the per-lot projection.
 *  Idempotent. Used by scripts/rebuild-read-models.ts. */
export async function rebuildFinishedLotPassport(
  tx: Tx,
): Promise<RebuildResult> {
  const lots = await tx
    .select({ id: finishedLots.id })
    .from(finishedLots);
  const result: RebuildResult = {
    scanned: lots.length,
    projected: 0,
    skipped: 0,
    totalRawBags: 0,
    totalOutputs: 0,
    totalPackagingLots: 0,
    totalQcEvents: 0,
  };
  for (const l of lots) {
    const r = await projectFinishedLotPassportForLot(tx, l.id);
    if (r.skipped) {
      result.skipped += 1;
      continue;
    }
    result.projected += 1;
    result.totalRawBags += r.rawBagsWritten;
    result.totalOutputs += r.outputsWritten;
    result.totalPackagingLots += r.packagingLotsWritten;
    result.totalQcEvents += r.qcEventsWritten;
  }
  return result;
}
