// Phase H.x3.5 — CSV export for PO reconciliation report.
//
// Streams one CSV containing the bag-level breakdown + the PO totals
// + the suggested-payable line. Used for supplier review or payment.
// Honest empty-state handling: missing values come through as empty
// cells, never zeroed.

import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth-guards";
import { derivePoRawMaterialReconciliation } from "@/lib/production/po-reconciliation";
import {
  derivePoBagAllocationReport,
  derivePoSplitUsageReport,
  derivePoSupplierDisputePacket,
} from "@/lib/production/bag-allocation";

export const dynamic = "force-dynamic";

function escape(v: unknown): string {
  if (v == null) return "";
  const s = String(v);
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function row(values: ReadonlyArray<unknown>): string {
  return values.map(escape).join(",") + "\n";
}

export async function GET(
  _req: Request,
  context: { params: Promise<{ poId: string }> },
) {
  const me = await requireAdmin();
  const { poId } = await context.params;
  const [recon, allocationLedger, splitUsage, disputePacket] = await Promise.all([
    derivePoRawMaterialReconciliation(poId),
    derivePoBagAllocationReport(poId),
    derivePoSplitUsageReport(poId),
    derivePoSupplierDisputePacket(poId),
  ]);
  if (!recon) {
    return new NextResponse("Not found", { status: 404 });
  }

  const generatedAt = new Date().toISOString();
  let csv = "";

  // Header.
  csv += row(["PO reconciliation report"]);
  csv += row(["Generated at", generatedAt]);
  csv += row(["Generated by", me.email ?? me.id]);
  csv += "\n";

  // Section 1 — PO summary.
  csv += row(["Section", "PO summary"]);
  csv += row(["PO number", recon.poNumber]);
  csv += row(["Vendor", recon.vendorName ?? ""]);
  csv += row(["Status", recon.status]);
  csv += row(["Raw items", recon.rawItemNames.join("; ")]);
  csv += row(["Bags received", recon.bagsReceived]);
  csv += row(["Vendor declared total (units)", recon.vendorDeclaredTotal.value ?? ""]);
  csv += row(["Received net weight (g)", recon.receivedNetWeightTotalGrams.value ?? ""]);
  csv += row(["Internal estimated total (units)", recon.internalEstimatedTotal.value ?? ""]);
  csv += row(["Finished equivalent (units)", recon.finishedEquivalentTotal.value ?? ""]);
  csv += row(["Known loss (units)", recon.knownLossTotal.value ?? ""]);
  csv += row(["Remaining estimate (units)", recon.remainingEstimateTotal.value ?? ""]);
  csv += row(["Unknown variance (units)", recon.unknownVariance.value ?? ""]);
  csv += row([
    "Variance %",
    typeof recon.variancePercent.value === "number"
      ? recon.variancePercent.value.toFixed(2)
      : "",
  ]);
  csv += row(["Combined confidence", recon.combinedConfidence]);
  csv += "\n";

  // Section 2 — Bag breakdown.
  csv += row(["Section", "Bag breakdown"]);
  csv += row([
    "Bag #",
    "Tablet",
    "Vendor barcode",
    "Status",
    "Vendor declared",
    "Net weight (g)",
    "Our estimate",
    "Finished equivalent",
    "Known loss",
    "Remaining",
    "Unknown variance",
    "Confidence",
  ]);
  for (const b of recon.bagBreakdown) {
    csv += row([
      b.bagNumber ?? "",
      b.tabletTypeName ?? "",
      b.vendorBarcode ?? "",
      b.status,
      b.vendorDeclaredCount.value ?? "",
      b.receivedNetWeightGrams.value ?? "",
      b.ourEstimatedCount.value ?? "",
      b.finishedEquivalentUnits.value ?? "",
      b.knownLossUnits.value ?? "",
      b.remainingEstimate.value ?? "",
      b.unknownVariance.value ?? "",
      b.combinedConfidence,
    ]);
  }
  csv += "\n";

  // Section 3 — Product/route allocation.
  csv += row(["Section", "Product / route allocation"]);
  csv += row([
    "Product",
    "SKU",
    "Route",
    "Raw consumed",
    "Finished units",
    "Displays",
    "Cases",
    "Damage/rework",
    "Yield %",
  ]);
  for (const a of recon.productAllocation) {
    csv += row([
      a.productName,
      a.productSku,
      a.routeCode ?? "",
      a.rawUnitsConsumed,
      a.finishedUnits,
      a.finishedDisplays,
      a.finishedCases,
      a.damageRework,
      a.yieldPercent != null ? a.yieldPercent.toFixed(2) : "",
    ]);
  }
  csv += "\n";

  // Section 4 — Cycle timeline.
  const tl = recon.cycleTimeline;
  csv += row(["Section", "Production cycle timeline"]);
  csv += row(["Received at", tl.receivedAt ?? ""]);
  csv += row(["First production start", tl.firstProductionStart ?? ""]);
  csv += row(["Last production end", tl.lastProductionEnd ?? ""]);
  csv += row(["Finished lots", tl.finishedLotsCount]);
  csv += row(["Active WIP bags", tl.activeWipBags]);
  csv += "\n";

  // Section 5 — Raw bag allocation ledger.
  csv += row(["Section", "Raw bag allocation ledger"]);
  csv += row([
    "Bag #",
    "Raw item",
    "Status",
    "Vendor count",
    "Allocated",
    "Consumed",
    "Returned",
    "Open WIP",
    "Remaining",
    "Known loss",
    "Unknown variance",
    "Confidence",
    "Legacy fallback",
  ]);
  for (const b of allocationLedger) {
    csv += row([
      b.bagNumber ?? "",
      b.rawItemName ?? "",
      b.status,
      b.vendorDeclaredCount ?? "",
      b.allocatedQty,
      b.consumedQty,
      b.returnedQty,
      b.openAllocationQty,
      b.remainingQtyEstimate ?? "",
      b.knownLossQty,
      b.unknownVarianceQty ?? "",
      b.confidence,
      b.fallbackUsed ? "true" : "false",
    ]);
  }
  csv += "\n";

  // Section 5b — Split usage by product.
  csv += row(["Section", "PO split usage by product"]);
  csv += row([
    "Product",
    "SKU",
    "Route",
    "Bags touched",
    "Consumed from PO",
    "Finished equivalent",
    "Damage/rework",
    "Yield %",
    "Share of PO %",
    "Confidence",
  ]);
  for (const s of splitUsage) {
    csv += row([
      s.productName,
      s.productSku,
      s.routeCode ?? "",
      s.bagsTouched,
      s.consumedFromPo,
      s.finishedEquivalent,
      s.damageRework,
      s.yieldPercent != null ? s.yieldPercent.toFixed(2) : "",
      s.shareOfPoConsumed != null ? s.shareOfPoConsumed.toFixed(2) : "",
      s.confidence,
    ]);
  }
  csv += "\n";

  // Section 6 — Vendor dispute / audit packet.
  if (disputePacket) {
    csv += row(["Section", "Vendor dispute / audit packet"]);
    csv += row(["Generated at", disputePacket.generatedAt]);
    csv += row(["Combined confidence", disputePacket.combinedConfidence]);
    csv += row(["Vendor declared total", disputePacket.vendorDeclaredTotal.value ?? ""]);
    csv += row(["Received weight total", disputePacket.ourReceivedWeightTotal.value ?? ""]);
    csv += row(["Card consumption", disputePacket.consumedByCard.value ?? ""]);
    csv += row(["Bottle consumption", disputePacket.consumedByBottle.value ?? ""]);
    csv += row(["Variety pack consumption", disputePacket.consumedByVarietyPack.value ?? ""]);
    csv += row(["Remaining total", disputePacket.remainingTotal.value ?? ""]);
    csv += row(["Known damage / rework", disputePacket.knownDamageRework.value ?? ""]);
    csv += row(["Unknown variance", disputePacket.unknownVariance.value ?? ""]);
    csv += "\n";
    csv += row(["Narrative"]);
    for (const line of disputePacket.narrative) csv += row([line]);
    csv += "\n";
  }

  // Section 7 — Settlement.
  const s = recon.settlement;
  csv += row(["Section", "Supplier settlement"]);
  csv += row(["Vendor declared total", s.vendorDeclaredTotal ?? ""]);
  csv += row(["Accounted finished output", s.accountedFinishedOutput ?? ""]);
  csv += row(["Known losses", s.knownLosses ?? ""]);
  csv += row(["Remaining inventory", s.remainingInventory ?? ""]);
  csv += row(["Unknown variance", s.unknownVariance ?? ""]);
  csv += row(["Suggested payable quantity (source)", s.suggestedPayable.source]);
  csv += row(["Suggested payable quantity (value)", s.suggestedPayable.value ?? ""]);
  csv += row(["Suggested payable explanation", s.suggestedPayable.explanation]);

  return new NextResponse(csv, {
    status: 200,
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="po-${recon.poNumber}-reconciliation.csv"`,
    },
  });
}
